repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
        name: Merge conflict protection
        stages: [commit]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.25.0
    hooks:
      - id: commitizen
        name: Commit message enforcement
        stages: [commit-msg]
  # - repo: local
  #   hooks:
  #     - id: unit-testing
  #       name: Unit testing
  #       stages: [commit]
  #       entry: make test
  #       language: system
  # - repo: local
  #   hooks:
  #     - id: security-scan
  #       name: Security scanning
  #       stages: [commit]
  #       entry: make sec-scan
  #       language: system
